---
output:
  html_document: 
    css: columns.css
  pdf_document: 
    keep_tex: true
    includes:
      in_header: columns.tex
---
# LE1
Du kannst Konvergenzeigenschaften und Grenzwert von einfachen Zahlenfolgen bestimmen - insbesondere auch von Folgen, welche iterative Lösungs-verfahren definieren (z.B. Heron Verfahren). 
Ausserdem kannst du den Grenzwert von Funktionen an ausgewählten Fällen berechnen und können damit auch die Stetigkeit von Funktionen untersuchen.  

Heron Verfahren?

# LE2







1. Am weitesten Links stehende Spalte identifizieren mit den meisten Nullen  
2. Ist die oberste Zahl dieser Spalte 0 -> mit geeigneter Zeile vertauschen  
3. Oberste Zeile durch a dividieren, um führende Eins zu erzeugen  
4. Addiere / Subtrahiere passende Vielfache, um unterhalb führende Nullen zu erzeugen.   
5. Repeat bis <span style="color: blue;">Zeilenstufenform</span> erreicht wurde.    
<span style="color: blue;">Lösung durch Rückeinsetzen: </span> $$\begin{bmatrix} 1 & 2 & 3 & 1 \\ 0 & 1 & 1 & \frac {1} {2} \\ 0 & 0 & 1 & \frac {1} {6} \end{bmatrix}$$
${z = \frac {1} {6}; y = \frac{1}{2}-1z = \frac{1}{3}; x = 1-3z-2y = - \frac{1}{6}}$  

6. Zeile bestimmen, die am weitesten rechts liegende führende Eins enthält.
7. Addiere passende Vielfachen dieser Zeile um oberhalb der Eins Nullen zu erzeugen.  
8. repeat bis <span style="color: blue">reduzierte Zeilenstufenform </span> erreicht wurde.  

$$\begin{bmatrix} 1 & 4 & 7 & 10 \\ 2 & 5 & 8 & 11 \\ 3 & 6 & 9 & 12 \end{bmatrix}$$  
$$\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$$  
$$\begin{bmatrix} 14 & 32 & 50 & 68 \\ 32 & 77 & 122 & 167 \end{bmatrix}$$  
$$\begin{bmatrix} a_{11} & a_{12} & a_{13} & a_{11} & a_{12} \\ a_{21} & a_{22} & a_{23} & a_{21} & a_{22} \\ a_{31} & a_{32} & a_{33} & a_{31} & a_{32} \end{bmatrix}$$ 
${1\cdot 1 + 2 \cdot 2 + 3 \cdot 3}$  
${4\cdot 7 + 5 \cdot 8 + 6 \cdot 9}$
<div class="Highlighted">
$\begin{aligned}
r _ {xy} ^{Sp} = \frac { s _ {rg(x),rg(x)} } { s _ {rg(x)} \cdot s _{rg(y)} }
\end{aligned}$  
</div>   